# This is a Docker Compose file for running a web application with Prometheus monitoring.
# It defines two services: the main application and Prometheus.
services:
  app:
    build: .
    container_name: heartfailure_app
    ports:
      - "7860:7860"
      - "8001:8001"  # Prometheus metrics
    expose:
      - "8001"
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml