global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'heartfailure-app'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['heartfailure_app:8001']